M48
; DRILL file {KiCad 7.0.10-1.fc39} date Tue 09 Jan 2024 04:30:15 PM EST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-09T16:30:15-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-1.fc39
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X218.3Y56.43
X218.3Y31.92
X265.25Y56.43
X265.25Y31.92
M30
